/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api.requests;

import com.amniscient.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DetectRequest.Builder.class)
public final class DetectRequest {
    private final String organizationId;

    private final Object file;

    private final Map<String, Object> additionalProperties;

    private DetectRequest(String organizationId, Object file, Map<String, Object> additionalProperties) {
        this.organizationId = organizationId;
        this.file = file;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Your organization identifier
     */
    @JsonProperty("organization_id")
    public String getOrganizationId() {
        return organizationId;
    }

    @JsonProperty("file")
    public Object getFile() {
        return file;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DetectRequest && equalTo((DetectRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DetectRequest other) {
        return organizationId.equals(other.organizationId) && file.equals(other.file);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organizationId, this.file);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OrganizationIdStage builder() {
        return new Builder();
    }

    public interface OrganizationIdStage {
        FileStage organizationId(@NotNull String organizationId);

        Builder from(DetectRequest other);
    }

    public interface FileStage {
        _FinalStage file(Object file);
    }

    public interface _FinalStage {
        DetectRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OrganizationIdStage, FileStage, _FinalStage {
        private String organizationId;

        private Object file;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DetectRequest other) {
            organizationId(other.getOrganizationId());
            file(other.getFile());
            return this;
        }

        /**
         * <p>Your organization identifier</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("organization_id")
        public FileStage organizationId(@NotNull String organizationId) {
            this.organizationId = Objects.requireNonNull(organizationId, "organizationId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("file")
        public _FinalStage file(Object file) {
            this.file = file;
            return this;
        }

        @java.lang.Override
        public DetectRequest build() {
            return new DetectRequest(organizationId, file, additionalProperties);
        }
    }
}
