/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class AmniscientApiException extends RuntimeException {
    public AmniscientApiException(String message) {
        super(message);
    }

    public AmniscientApiException(String message, Exception e) {
        super(message, e);
    }
}
