/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api.core;

public final class Environment {
    public static final Environment DEFAULT =
            new Environment("https://tytbrazyv9.execute-api.us-east-1.amazonaws.com/prod/inference");

    private final String url;

    private Environment(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public static Environment custom(String url) {
        return new Environment(url);
    }
}
