/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api.errors;

import com.amniscient.api.core.AmniscientApiApiException;
import com.amniscient.api.types.UnauthorizedErrorBody;

public final class UnauthorizedError extends AmniscientApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final UnauthorizedErrorBody body;

    public UnauthorizedError(UnauthorizedErrorBody body) {
        super("UnauthorizedError", 401, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public UnauthorizedErrorBody body() {
        return this.body;
    }
}
