/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api.resources.detection;

import com.amniscient.api.core.AmniscientApiApiException;
import com.amniscient.api.core.AmniscientApiException;
import com.amniscient.api.core.ClientOptions;
import com.amniscient.api.core.ObjectMappers;
import com.amniscient.api.core.RequestOptions;
import com.amniscient.api.errors.BadRequestError;
import com.amniscient.api.resources.detection.requests.DetectionDetectRequest;
import com.amniscient.api.resources.detection.types.DetectionDetectResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class DetectionClient {
    protected final ClientOptions clientOptions;

    public DetectionClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Detects an object within an uploaded image file. Make sure to load the model you're using for detection first!
     */
    public DetectionDetectResponse detect(DetectionDetectRequest request) {
        return detect(request, null);
    }

    /**
     * Detects an object within an uploaded image file. Make sure to load the model you're using for detection first!
     */
    public DetectionDetectResponse detect(DetectionDetectRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("detect")
                .build();
        MultipartBody.Builder body = new MultipartBody.Builder().setType(MultipartBody.FORM);
        try {
            body.addFormDataPart(
                    "organization_id", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getOrganizationId()));
            body.addFormDataPart("file", ObjectMappers.JSON_MAPPER.writeValueAsString(request.getFile()));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("POST", body.build())
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), DetectionDetectResponse.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                if (response.code() == 400) {
                    throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new AmniscientApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        } catch (IOException e) {
            throw new AmniscientApiException("Network error executing HTTP request", e);
        }
    }
}
