/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api;

import com.amniscient.api.core.ClientOptions;
import com.amniscient.api.core.RequestOptions;
import com.amniscient.api.requests.DetectRequest;
import com.amniscient.api.requests.LoadModelRequest;
import com.amniscient.api.types.DetectResponse;
import java.io.File;
import java.util.List;

public class AmniscientApiClient {
    protected final ClientOptions clientOptions;

    private final RawAmniscientApiClient rawClient;

    public AmniscientApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAmniscientApiClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAmniscientApiClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Initializes a model for inference. This endpoint must be called before running any detections.
     */
    public List<String> loadModel(String modelId, LoadModelRequest request) {
        return this.rawClient.loadModel(modelId, request).body();
    }

    /**
     * Initializes a model for inference. This endpoint must be called before running any detections.
     */
    public List<String> loadModel(String modelId, LoadModelRequest request, RequestOptions requestOptions) {
        return this.rawClient.loadModel(modelId, request, requestOptions).body();
    }

    /**
     * Detects an object within an uploaded image file. Make sure to load the model you're using for detection first!
     */
    public DetectResponse detect(File file, DetectRequest request) {
        return this.rawClient.detect(file, request).body();
    }

    /**
     * Detects an object within an uploaded image file. Make sure to load the model you're using for detection first!
     */
    public DetectResponse detect(File file, DetectRequest request, RequestOptions requestOptions) {
        return this.rawClient.detect(file, request, requestOptions).body();
    }

    public static AmniscientApiClientBuilder builder() {
        return new AmniscientApiClientBuilder();
    }
}
