/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.amniscient.api;

import com.amniscient.api.core.ClientOptions;
import com.amniscient.api.core.Suppliers;
import com.amniscient.api.resources.detection.DetectionClient;
import com.amniscient.api.resources.model.ModelClient;
import java.util.function.Supplier;

public class AmniscientApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ModelClient> modelClient;

    protected final Supplier<DetectionClient> detectionClient;

    public AmniscientApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.modelClient = Suppliers.memoize(() -> new ModelClient(clientOptions));
        this.detectionClient = Suppliers.memoize(() -> new DetectionClient(clientOptions));
    }

    public ModelClient model() {
        return this.modelClient.get();
    }

    public DetectionClient detection() {
        return this.detectionClient.get();
    }

    public static AmniscientApiClientBuilder builder() {
        return new AmniscientApiClientBuilder();
    }
}
